// 常量定义

export const REQUEST_TYPES = {
  XHR: 'xhr',
  FETCH: 'fetch',
  WEBSOCKET: 'websocket'
};

export const STORAGE_TYPES = {
  LOCAL_STORAGE: 'localStorage',
  SESSION_STORAGE: 'sessionStorage',
  COOKIES: 'cookies'
};

export const EXPORT_FORMATS = {
  JSON: 'json',
  HAR: 'har'
};

export const MESSAGE_TYPES = {
  START_RECORDING: 'START_RECORDING',
  STOP_RECORDING: 'STOP_RECORDING',
  GET_STATUS: 'GET_STATUS',
  CAPTURE_REQUEST: 'CAPTURE_REQUEST',
  CAPTURE_STORAGE: 'CAPTURE_STORAGE',
  GET_SESSIONS: 'GET_SESSIONS',
  GET_SESSION: 'GET_SESSION',
  DELETE_SESSION: 'DELETE_SESSION',
  EXPORT_SESSION: 'EXPORT_SESSION',
  START_PLAYBACK: 'START_PLAYBACK',
  STOP_PLAYBACK: 'STOP_PLAYBACK'
};
